[tls]
certificate_path = "tests/tls/server.cert"
private_key_path = "tests/tls/server.key"

# To directly provide PEM contents:
# certificate_pem = """-----BEGIN CERTIFICATE-----
# ...your certificate content here...
# -----END CERTIFICATE-----
# """
# private_key_pem = """-----BEGIN PRIVATE KEY-----
# ...your private key content here...
# -----END PRIVATE KEY-----
# """

[database]
name = "cipherstash"
username = "cipherstash"
password = "password"
with_tls = true

[auth]
workspace_crn = "workspace_crn"
client_access_key = "client_access_key"

[encrypt]
default_keyset_id = "00000000-0000-0000-0000-000000000000"
client_id = "00000000-0000-0000-0000-000000000000"
client_key = "client_key"
